/*
 * File: app/store/StTreeSprav.js
 * Date: Wed Dec 04 2019 00:13:55 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osmd.store.StTreeSprav', {
    extend: 'Ext.data.TreeStore',
    alias: 'store.stTreeSprav',

    requires: [
        'Osmd.model.MdTreeOrg',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'stTreeSprav',
            model: 'Osmd.model.MdTreeOrg',
            root: {
                expanded: true,
                children: [
                    {
                        id: 'sprav',
                        text: 'Справочники',
                        expanded: false,
                        children: [
                            {
                                id: 'tabLgota',
                                leaf: true,
                                text: 'Справочник льгот'
                            },
                            {
                                id: 'tabTarif',
                                leaf: true,
                                text: 'Справочник тарифов'
                            }
                        ]
                    },
                    {
                        id: 'AppHistory',
                        leaf: true,
                        text: 'Изменения по квартирам'
                    },
                    {
                        id: 'SchetOsmd',
                        leaf: true,
                        text: 'Уведомления'
                    },
                    {
                        id: 'DolgWarningSummaOsmd',
                        leaf: true,
                        text: 'Предупреждения'
                    },
                    {
                        id: 'InfoHouse',
                        leaf: true,
                        text: 'Характеристика дома'
                    },
                    {
                        id: 'ItogMonthOsmd',
                        leaf: true,
                        text: 'Итоговый по ОСМД'
                    },
                    {
                        id: 'ItogMonthOsmdHouse',
                        leaf: true,
                        text: 'Итоговый по дому'
                    },
                    {
                        id: 'NachislenoAllHouseOsmd',
                        leaf: true,
                        text: 'Начислено по дому'
                    },
                    {
                        id: 'DolgiOsmd',
                        leaf: true,
                        text: 'Должники'
                    },
                    {
                        id: 'ControlOsmd',
                        leaf: true,
                        text: 'Контроль'
                    },
                    {
                        id: 'KvKassa',
                        text: 'Касса',
                        expanded: false,
                        children: [
                            {
                                id: 'KassaAddressOsmd',
                                leaf: true,
                                text: 'Реестр по адресам'
                            },
                            {
                                id: 'KassaPrixodOsmd',
                                leaf: true,
                                text: 'Реестр по кассе'
                            },
                            {
                                id: 'KassaDateOsmd',
                                leaf: true,
                                text: 'Реестр по дате'
                            }
                        ]
                    },
                    {
                        id: 'Budjet',
                        text: 'Бюджет',
                        expanded: false,
                        children: [
                            {
                                id: 'ItogBudjetPoGroupOsmd',
                                leaf: true,
                                text: 'Свод по группам льгот'
                            },
                            {
                                id: 'ItogBudjetPoGroupRazvOsmd',
                                leaf: true,
                                text: 'Разв по группам льгот'
                            },
                            {
                                id: 'tabHouseResidents',
                                leaf: true,
                                text: 'Справка для субсидий'
                            }
                        ]
                    },
                    {
                        id: 'BudjetOsmd',
                        text: 'АДМИН',
                        expanded: false,
                        children: [
                            {
                                id: 'tabOrg',
                                leaf: true,
                                text: 'Информация по ОСМД'
                            },
                            {
                                id: 'ReestrOwner',
                                leaf: true,
                                text: 'Реестр совладельцев'
                            },
                            {
                                id: 'tabKvartplata',
                                leaf: true,
                                text: 'Тариф и начисление'
                            },
                            {
                                id: 'ControlAllOsmd',
                                leaf: true,
                                text: 'Контроль по ОСМД'
                            },
                            {
                                id: 'NachislenoAllOsmd',
                                leaf: true,
                                text: 'Начислено по ОСМД'
                            },
                            {
                                id: 'tabPrivatBank',
                                leaf: true,
                                text: 'Оплата Приватбанк'
                            },
                            {
                                id: 'Lgota',
                                text: 'Льготы',
                                expanded: false,
                                children: [
                                    {
                                        id: 'tabLgotnik',
                                        leaf: true,
                                        text: 'Льготники'
                                    },
                                    {
                                        id: 'tabSprUtszn',
                                        leaf: true,
                                        text: 'Справочник для УТиСЗН'
                                    },
                                    {
                                        id: 'ItogBudjetPoGroupOsmdSv',
                                        leaf: true,
                                        text: 'Свод по группам по дому'
                                    },
                                    {
                                        id: 'ItogBudjetPoGroupRazvOsmdSv',
                                        leaf: true,
                                        text: 'Разв по группам льгот'
                                    },
                                    {
                                        id: 'PrintLgotaUtsznAll',
                                        leaf: true,
                                        text: 'Свод льгот все ОСМД'
                                    },
                                    {
                                        id: 'ItogBudjetPoGroupOsmdAll',
                                        leaf: true,
                                        text: 'Свод по группе все ОСМД'
                                    },
                                    {
                                        id: 'tabDbfLgota',
                                        leaf: true,
                                        text: 'Отправка льгот в УТиСЗН'
                                    },
                                    {
                                        id: 'tabLgotaUtszn',
                                        leaf: true,
                                        text: 'Сверка по Льготникам'
                                    }
                                ]
                            },
                            {
                                id: 'Subsidia',
                                text: 'Субсидии',
                                expanded: false,
                                children: [
                                    {
                                        id: 'tabSubsidia',
                                        leaf: true,
                                        text: 'Субсидия'
                                    },
                                    {
                                        id: 'PrintSubsUtsznAll',
                                        leaf: true,
                                        text: 'Свод субсидий по ОСМД'
                                    },
                                    {
                                        id: 'DolgiOsmdSubs',
                                        leaf: true,
                                        text: 'Должники по Субсидиям'
                                    },
                                    {
                                        id: 'tabSubsUtszn',
                                        leaf: true,
                                        text: 'Сверка по Субсидиям'
                                    },
                                    {
                                        id: 'tabVozvratSubsidia',
                                        leaf: true,
                                        text: 'Возврат Субсидий'
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            proxy: {
                type: 'ajax',
                url: 'local',
                reader: {
                    type: 'json'
                }
            }
        }, cfg)]);
    }
});