/*
 * File: app/model/MdHouses.js
 * Date: Thu May 04 2017 21:49:37 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osmd.model.MdHouses', {
    extend: 'Ext.data.Model',
    alias: 'model.mdHouses',

    requires: [
        'Ext.data.field.Integer',
        'Ext.data.field.String'
    ],

    fields: [
        {
            type: 'int',
            name: 'raion_id'
        },
        {
            type: 'int',
            name: 'street_id'
        },
        {
            type: 'int',
            name: 'house_id'
        },
        {
            type: 'int',
            name: 'address_id'
        },
        {
            type: 'string',
            name: 'house'
        },
        {
            type: 'string',
            name: 'raion'
        },
        {
            type: 'string',
            name: 'street'
        },
        {
            type: 'string',
            name: 'item'
        },
        {
            type: 'string',
            name: 'address'
        },
        {
            type: 'string',
            name: 'appartment'
        },
        {
            type: 'int',
            name: 'edrpou'
        },
        {
            type: 'string',
            name: 'abbr'
        },
        {
            type: 'int',
            name: 'osmd_id'
        },
        {
            type: 'string',
            name: 'osmd'
        }
    ]
});