/*
 * File: app/model/MdPriborUcheta.js
 * Date: Thu Dec 08 2016 23:44:05 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osmd.model.MdPriborUcheta', {
    extend: 'Ext.data.Model',
    alias: 'model.mdPriborUcheta',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Date',
        'Ext.data.field.Number',
        'Ext.data.field.Boolean'
    ],

    fields: [
        {
            type: 'int',
            name: 'pok_id'
        },
        {
            type: 'int',
            name: 'teplomer_id'
        },
        {
            type: 'int',
            name: 'dteplomer_id'
        },
        {
            type: 'int',
            name: 'dvodomer_id'
        },
        {
            type: 'int',
            name: 'vodomer_id'
        },
        {
            type: 'int',
            name: 'address_id'
        },
        {
            type: 'int',
            name: 'house_id'
        },
        {
            type: 'int',
            name: 'mop_id'
        },
        {
            type: 'int',
            name: 'mopid'
        },
        {
            type: 'string',
            name: 'house'
        },
        {
            type: 'string',
            name: 'name'
        },
        {
            type: 'int',
            name: 'raion_id'
        },
        {
            type: 'string',
            name: 'raion'
        },
        {
            type: 'int',
            name: 'filial_id'
        },
        {
            type: 'int',
            name: 'org_id'
        },
        {
            type: 'int',
            name: 'model_id'
        },
        {
            type: 'int',
            name: 'obr'
        },
        {
            type: 'string',
            name: 'appartment'
        },
        {
            type: 'string',
            name: 'vvod'
        },
        {
            type: 'string',
            name: 'address'
        },
        {
            type: 'string',
            name: 'period'
        },
        {
            type: 'string',
            name: 'filial'
        },
        {
            type: 'string',
            name: 'org'
        },
        {
            type: 'string',
            name: 'nomer'
        },
        {
            type: 'string',
            name: 'model'
        },
        {
            type: 'string',
            name: 'type'
        },
        {
            type: 'string',
            name: 'place'
        },
        {
            name: 'position'
        },
        {
            type: 'date',
            name: 'data'
        },
        {
            type: 'date',
            name: 'fdate'
        },
        {
            type: 'date',
            name: 'pdate'
        },
        {
            type: 'date',
            name: 'sdate'
        },
        {
            type: 'date',
            name: 'data_spis'
        },
        {
            type: 'float',
            name: 'newValue'
        },
        {
            type: 'float',
            name: 'pred'
        },
        {
            type: 'float',
            name: 'tek'
        },
        {
            type: 'float',
            name: 'tekp'
        },
        {
            type: 'float',
            name: 'kub'
        },
        {
            type: 'int',
            name: 'people'
        },
        {
            type: 'int',
            name: 'personal'
        },
        {
            type: 'string',
            name: 'edizm'
        },
        {
            type: 'float',
            name: 'volume'
        },
        {
            type: 'float',
            name: 'temp'
        },
        {
            type: 'float',
            name: 'gkm3'
        },
        {
            type: 'float',
            name: 'gkm2'
        },
        {
            type: 'float',
            name: 'gkm2_mop'
        },
        {
            type: 'float',
            name: 'gkal'
        },
        {
            type: 'float',
            name: 'gkal_gvva'
        },
        {
            type: 'float',
            name: 'gkal_gvna'
        },
        {
            type: 'float',
            name: 'gkal_gvvo'
        },
        {
            type: 'float',
            name: 'gkal_gvno'
        },
        {
            type: 'float',
            name: 'gkal_gv'
        },
        {
            type: 'float',
            name: 'gkal_dt'
        },
        {
            type: 'float',
            name: 'gkal_mop'
        },
        {
            type: 'float',
            name: 'gkal_otsa'
        },
        {
            type: 'float',
            name: 'gkal_otso'
        },
        {
            type: 'float',
            name: 'gkal_otto'
        },
        {
            type: 'float',
            name: 'gkal_otta'
        },
        {
            type: 'float',
            name: 'gkal_year'
        },
        {
            type: 'float',
            name: 'gkal_nach'
        },
        {
            type: 'float',
            name: 'gkub_o'
        },
        {
            type: 'float',
            name: 'gkub_a'
        },
        {
            type: 'int',
            name: 'day_hh'
        },
        {
            type: 'int',
            name: 'day_dt'
        },
        {
            type: 'int',
            name: 'day_gv'
        },
        {
            type: 'int',
            name: 'day_middle'
        },
        {
            type: 'int',
            name: 'day_ot'
        },
        {
            type: 'date',
            name: 'date_pred'
        },
        {
            type: 'string',
            name: 'koef'
        },
        {
            type: 'float',
            name: 'tarif_xv'
        },
        {
            type: 'float',
            name: 'tarif'
        },
        {
            type: 'float',
            name: 'tarif_gv'
        },
        {
            type: 'float',
            name: 'tarif_st'
        },
        {
            type: 'float',
            name: 'budjet'
        },
        {
            type: 'float',
            name: 'xvoda'
        },
        {
            type: 'float',
            name: 'qty'
        },
        {
            type: 'int',
            name: 'out'
        },
        {
            type: 'string',
            name: 'voda'
        },
        {
            type: 'float',
            name: 'gvoda'
        },
        {
            type: 'date',
            name: 'data_in'
        },
        {
            type: 'float',
            name: 'stoki'
        },
        {
            type: 'float',
            name: 'otoplenie'
        },
        {
            type: 'float',
            name: 'xkub_lg'
        },
        {
            type: 'float',
            name: 'gkub_lg'
        },
        {
            type: 'float',
            name: 'lgota_xv'
        },
        {
            type: 'float',
            name: 'lgota_gv'
        },
        {
            type: 'float',
            name: 'lgota_st'
        },
        {
            type: 'string',
            name: 'note'
        },
        {
            type: 'float',
            name: 'money_otto'
        },
        {
            type: 'float',
            name: 'money_otta'
        },
        {
            type: 'float',
            name: 'money_otsa'
        },
        {
            type: 'float',
            name: 'money_otso'
        },
        {
            type: 'float',
            name: 'area_dt'
        },
        {
            type: 'float',
            name: 'area'
        },
        {
            type: 'float',
            name: 'area_dta'
        },
        {
            type: 'float',
            name: 'area_all'
        },
        {
            type: 'float',
            name: 'area_lg'
        },
        {
            type: 'float',
            name: 'area_ta'
        },
        {
            type: 'float',
            name: 'area_dto'
        },
        {
            type: 'float',
            name: 'area_ono'
        },
        {
            type: 'float',
            name: 'area_to'
        },
        {
            type: 'float',
            name: 'area_ano'
        },
        {
            type: 'float',
            name: 'gkm2_hh'
        },
        {
            type: 'date',
            name: 'date_ot'
        },
        {
            type: 'float',
            name: 'area_nach'
        },
        {
            type: 'float',
            name: 'nachisleno'
        },
        {
            type: 'float',
            name: 'budjet_sa'
        },
        {
            type: 'float',
            name: 'dolg'
        },
        {
            name: 'operator'
        },
        {
            type: 'string',
            name: 'content'
        },
        {
            type: 'float',
            name: 'tempr'
        },
        {
            type: 'int',
            name: 'joint'
        },
        {
            type: 'int',
            name: 'isjoint'
        },
        {
            type: 'int',
            name: 'hot'
        },
        {
            type: 'float',
            name: 'norma'
        },
        {
            type: 'int',
            name: 'st'
        },
        {
            type: 'float',
            name: 'pstoki'
        },
        {
            type: 'int',
            name: 'qty_hour'
        },
        {
            type: 'int',
            name: 'first_app'
        },
        {
            type: 'int',
            name: 'last_app'
        },
        {
            type: 'boolean',
            name: 'vodomer'
        },
        {
            type: 'int',
            name: 'nrx_gvs_d'
        },
        {
            type: 'string',
            name: 'plomba'
        },
        {
            type: 'string',
            name: 'zplomba'
        },
        {
            type: 'date',
            name: 'fpdate'
        },
        {
            type: 'int',
            name: 'vd'
        },
        {
            type: 'float',
            name: 'gkalm2'
        },
        {
            type: 'date',
            name: 'date_ar'
        },
        {
            type: 'date',
            name: 'date_ao'
        },
        {
            type: 'date',
            name: 'date_st'
        },
        {
            type: 'date',
            name: 'date_fin'
        },
        {
            type: 'int',
            name: 'pok_ot'
        },
        {
            type: 'int',
            name: 'pok_do'
        },
        {
            type: 'float',
            name: 'kub_day'
        },
        {
            type: 'int',
            name: 'qty_kub'
        },
        {
            type: 'int',
            name: 'rday'
        },
        {
            type: 'int',
            name: 'mday'
        },
        {
            type: 'int',
            name: 'allapp'
        }
    ]
});