/*
 * File: app/model/MdTarif.js
 * Date: Mon Jan 15 2018 19:38:31 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osmd.model.MdTarif', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.field.String',
        'Ext.data.field.Number',
        'Ext.data.field.Date'
    ],

    fields: [
        {
            type: 'int',
            name: 'raion'
        },
        {
            type: 'int',
            name: 'house_id'
        },
        {
            type: 'string',
            name: 'house'
        },
        {
            type: 'float',
            name: 'kv9'
        },
        {
            type: 'float',
            name: 'kv9f1'
        },
        {
            type: 'float',
            name: 'kv16'
        },
        {
            type: 'float',
            name: 'kv16f1'
        },
        {
            type: 'float',
            name: 'ch_kv9'
        },
        {
            type: 'float',
            name: 'ch_kv9f1'
        },
        {
            type: 'float',
            name: 'ch_kv16'
        },
        {
            type: 'float',
            name: 'ch_kv16f1'
        },
        {
            type: 'int',
            name: 'floor'
        },
        {
            type: 'date',
            name: 'data'
        },
        {
            type: 'float',
            name: 'lg'
        },
        {
            type: 'float',
            name: 'lgf1'
        },
        {
            type: 'float',
            name: 'dop'
        },
        {
            type: 'float',
            name: 'remont'
        }
    ]
});