/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'MdLgotnik',
        'MdHouses',
        'MdOrg',
        'MdOplata',
        'MdOrgCat',
        'MdOrgDog',
        'MdKoef',
        'MdUtszn',
        'MdUser',
        'MdPrixod',
        'MdTekNach',
        'MdStreet',
        'MdTekNachKassa',
        'MdLoginLocal',
        'MdTreeOrg',
        'MdAddress',
        'MdAppartment',
        'MdDbfLgota',
        'MdLogin',
        'MdRaion',
        'MdCheckAddress',
        'MdOrgPhones',
        'MdTarif'
    ],
    stores: [
        'StLoginLocal',
        'StTreeSprav',
        'StHAppartment',
        'StHVodomer',
        'StOplata',
        'StPrixod',
        'StReport',
        'StLgotnik',
        'StKvTarif',
        'StStreet',
        'StTekPokVodomera',
        'StHTeplomer',
        'StLgotaNachVoda',
        'stSubsidiaUtszn',
        'StUser',
        'StTekNach',
        'StTekNachKassa',
        'StDbfLgota',
        'StTekPokVodomerov',
        'StAppartment',
        'StTeplomer',
        'StAllPokTeplomera',
        'StAddress',
        'StVodomerKassa',
        'StLgota',
        'StLogin',
        'StVodomer',
        'StRaion',
        'StTarif',
        'StTekNachApp',
        'StWater',
        'StHATeplomer',
        'StHousesOrg',
        'StTekOplata',
        'StLgotnikTab',
        'StTekPokTeplomerov',
        'StTekPokTeplomera',
        'StHouses',
        'StAddressOrg',
        'StSubsidia',
        'stLgotaUtszn',
        'StOrg',
        'StSprUtszn',
        'StOsmd',
        'StHousesOsmd',
        'StAppartmentOsmd',
        'StFamaly',
        'StRodstvo',
        'StDocument',
        'StEdIzm1',
        'StOwner',
        'StDocOwner',
        'StPrivatBank',
        'StPrixodEdit'
    ],
    views: [
        'flat.TabAppVodomer',
        'menu.TabPnCenter',
        'menu.TabPnLeft',
        'sprav.TabLgotnik',
        'sprav.TabLogin',
        'sprav.TabReportOrg',
        'user.FmLogin',
        'VpKommuna',
        'NFieldVodomer',
        'NField',
        'FieldNach',
        'NFTarif',
        'sprav.TabSubsidia',
        'flat.TabOplata',
        'sprav.TabLgota',
        'user.WinLogin',
        'sprav.WinReport',
        'flat.TabAppTeplomer',
        'flat.TabNachApp',
        'sprav.TabKvartplata',
        'sprav.WinImport',
        'sprav.WinAddLgotaPerer',
        'sprav.WinExportLgota',
        'sprav.WinEditOplata',
        'sprav.TabSubsUtszn',
        'sprav.TabLgotaUtszn',
        'sprav.TabTarif',
        'sprav.TabHouseResidents',
        'flat.WinLgotnik',
        'sprav.WinPrintAktUtszn',
        'sprav.WinEditDbfLgota',
        'sprav.TabDbfLgota',
        'flat.WinFamaly',
        'flat.TabKassa',
        'sprav.TabVozvratSubsidia',
        'flat.WinOwner',
        'flat.TabOrg',
        'sprav.TabPrivatBank',
        'flat.TabAppBti'
    ],
    controllers: [
        'CrBti',
        'CrLeftMenu',
        'CrLogin',
        'Vodomer',
        'CrKassa',
        'CrInfo',
        'AppNach'
    ],
    name: 'Osmd',

    launch: function() {
        Ext.create('Osmd.view.VpKommuna');
        Ext.grid.RowEditor.prototype.saveBtnText = 'Записать';
        Ext.grid.RowEditor.prototype.cancelBtnText = 'Отменить';
        Ext.event.Event.resolveTextNode = function(node) {
            try {
                return (node && node.nodeType === 3) ? node.parentNode : node;
            } catch (err) {
                // ignore any errors here
                return null;
            }
        };
        //закрываем значок загрузка...
        var loading =Ext.get('loading');
        if(loading){
            setTimeout(function(){

                loading.remove();
                // Ext.get('loading-mask').fadeOut({remove:true});
            }, 250);
        }
    }

});
