/*
 * File: app/controller/CrLeftMenu.js
 * Date: Fri Apr 20 2018 10:34:09 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osmd.controller.CrLeftMenu', {
    extend: 'Ext.app.Controller',
    alias: 'controller.crLeftMenu',

    stores: [
        'StAddressOrg'
    ],
    views: [
        'VpKommuna',
        'menu.TabPnCenter'
    ],

    refs: {
        CbRaion: '#cbRaion',
        ListHouses: '#listHouses',
        ListHousesData: 'listHouses dataview',
        CbStreet: '#cbStreet',
        ShowAddress: '#showAddress',
        VpKommuna: '#vpKommuna',
        TabPnCenter: '#tabPnCenter'
    },

    control: {
        "#listHousesView": {
            itemclick: 'onListHousesViewItemClick'
        },
        "#tabMenuLifeFond": {
            activate: 'onTabMenuLifeFondActivate'
        },
        "#tabMenuSprav": {
            activate: 'onPanelActivate'
        },
        "#cbHouse": {
            select: 'onCbHouseSelect'
        }
    },

    onListHousesViewItemClick: function(dataview, record, item, index, e, eOpts) {
        //in use
        var me = this;
        var showAddress = Ext.getCmp('showAddress');

        // STORE

        var stUser = Ext.data.StoreManager.get("StUser");

        //LOGIN & PASSWORD

        var values =stUser.getAt(0);
        var login = values.get('login');
        var password = values.get('password');

        //LOGIKA

        var selected = record.data;
        if (selected){
               // console.log(selected);

            values.set({'osmd_id':selected.osmd_id,
                        'house_id':selected.house_id,
                        'house':selected.house,
                        'address_id':selected.address_id,
                        'address':selected.address,
                        'raion_id':selected.raion_id,
                        'raion':selected.raion,
                        'appartment':selected.appartment,
                        'street_id':selected.street_id,
                        'vibor':"app"
                       });
           // console.log(values);


            showAddress.setText(selected.address).show();
            me.LoadFlatData(true);

        }

    },

    onTabMenuLifeFondActivate: function(component, eOpts) {
        //TAB
        var me = this;

        var tabPnCenter = me.getTabPnCenter();
        //LOGIKA


                //КВАРТИРЫ
                tabPnCenter.child('#tabAppBti').tab.hide();
                tabPnCenter.child('#tabKassa').tab.hide();
                tabPnCenter.child('#tabNachApp').tab.hide();
                tabPnCenter.child('#tabOplata').tab.hide();

                tabPnCenter.child('#tabAppVodomer').tab.hide();
                tabPnCenter.child('#tabAppTeplomer').tab.hide();

                tabPnCenter.child('#tabLogin').tab.hide();
                tabPnCenter.setActiveTab('tabLogin');


    },

    onPanelActivate: function(component, eOpts) {
        //in use
        var me=this;
        //TAB
        var tabPnCenter = me.getTabPnCenter();

        tabPnCenter.child('#tabLogin').tab.hide();
        tabPnCenter.setActiveTab('tabLogin');
    },

    onCbHouseSelect: function(combo, record, eOpts) {
        //in use
        var me=this;
        /*
        COMPONENT
        */
        //var cbRaion = me.getCbRaion();
        var viewHouses = me.getListHousesData();
        /*
        STORE
        */
        var stUser = Ext.data.StoreManager.get("StUser");
        var StAddress = Ext.data.StoreManager.get("StAddress");
        /*
        LOGIN & PASSWORD
        */
        var values =stUser.getAt(0);
        var login = values.get('login');
        var password = values.get('password');
        values.set({'house_id':record.get('house_id')});
        stUser.sync();

        /*
        LOGIKA
        */
        //cbRaion.clearValue();
        if (record) {
            StAddress.load({
                params: {
                    what:'kvartira',
                    house_id: record.get('house_id'),
                    login:login,
                    password:password
                },
                scope: this
            });
        }
    },

    LoadFlatData: function(adr) {

        //in use
        var me = this;
        var crKassa = this.application.getController('CrKassa');

        //TAB_PANEL
        // Активный таб
        //console.log(activeTab);
        var tabPnCenter = me.getTabPnCenter();
        var activeTab = tabPnCenter.getActiveTab();
        var nameactiveTab = activeTab.getXType();
        var index = tabPnCenter.items.indexOf(activeTab);

        //STORE

        var stUser = Ext.data.StoreManager.get("StUser");

        //LOGIN & PASSWORD

        var values =stUser.getAt(0);
        var login = values.get('login');
        var password = values.get('password');
        var address_id = values.get('address_id');
        var address = values.get('address');
        var house_id = values.get('house_id');
        var prixod_id = values.get('prixod_id');

        //LOGIKA
        values.set({'dteplomer_id':0});
        stUser.sync();

        //КВАРТИРЫ
        tabPnCenter.child('#tabAppBti').tab.show();
        tabPnCenter.child('#tabKassa').tab.show();
        tabPnCenter.child('#tabNachApp').tab.show();
        tabPnCenter.child('#tabOplata').tab.show();
        tabPnCenter.child('#tabAppVodomer').tab.show();
        tabPnCenter.child('#tabAppTeplomer').tab.show();
        tabPnCenter.child('#tabLogin').tab.hide();
        var tab = tabPnCenter.child('#tabKassa');
        tab.setTitle(address);

        if (nameactiveTab==='tabkassa'){
            crKassa.onTabKassaActivate();
        } else {
            tabPnCenter.setActiveTab('tabKassa');
        }





    }

});
