/*
 * File: app/view/flat/TabAppTeplomer.js
 * Date: Thu May 21 2020 17:42:54 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osmd.view.flat.TabAppTeplomer', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tabAppTeplomer',

    requires: [
        'Osmd.view.flat.TabAppTeplomerViewModel',
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.form.FieldContainer',
        'Ext.form.field.Date',
        'Ext.form.field.Number',
        'Ext.form.FieldSet'
    ],

    viewModel: {
        type: 'tabAppTeplomer'
    },
    height: 547,
    hidden: true,
    id: 'tabAppTeplomer',
    width: 1031,
    layout: 'fit',
    title: 'Тепломеры',

    items: [
        {
            xtype: 'form',
            id: 'fmAppTeplomer',
            itemId: 'fmAppTeplomer',
            scrollable: true,
            bodyPadding: 10,
            icon: '',
            title: '',
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'grAppHTeplomer',
                    margin: '5 5 15 5',
                    width: 778,
                    collapsed: true,
                    collapsible: true,
                    title: 'Тепломеры снятые с учета',
                    emptyText: 'Приборов учета снятых с учета нет',
                    store: 'StHTeplomer',
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            width: 50,
                            dataIndex: 'dteplomer_id',
                            text: 'Дт',
                            format: '0'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            width: 63,
                            dataIndex: 'teplomer_id',
                            menuDisabled: true,
                            text: 'Ид',
                            format: '0'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 141,
                            dataIndex: 'model',
                            menuDisabled: true,
                            text: 'Модель'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 111,
                            dataIndex: 'nomer',
                            menuDisabled: true,
                            text: 'Номер'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 94,
                            dataIndex: 'sdate',
                            menuDisabled: true,
                            text: 'дата пост',
                            format: 'd-m-Y'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 94,
                            dataIndex: 'data_spis',
                            menuDisabled: true,
                            text: 'Списан'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 65,
                            dataIndex: 'edizm',
                            menuDisabled: true,
                            text: 'Ед.изм'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 97,
                            dataIndex: 'koef',
                            menuDisabled: true,
                            text: 'коеф'
                        },
                        {
                            xtype: 'numbercolumn',
                            dataIndex: 'area',
                            menuDisabled: true,
                            text: 'S (м&sup2;)'
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    id: 'grAppTeplomer',
                    margin: 5,
                    width: 778,
                    title: 'Тепломеры',
                    emptyText: 'Тепломеров нет',
                    store: 'StTeplomer',
                    viewConfig: {
                        emptyText: 'Тепломеров нет'
                    },
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            width: 45,
                            dataIndex: 'dteplomer_id',
                            text: 'Дт',
                            format: '0'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if (record.get('out')===1){
                                    metaData.tdCls = 'line-through';
                                }
                                return value;
                            },
                            width: 196,
                            dataIndex: 'model',
                            menuDisabled: true,
                            text: 'Модель'
                        },
                        {
                            xtype: 'gridcolumn',
                            renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                if (record.get('out')===1){
                                    metaData.tdCls = 'line-through';
                                }
                                return value;
                            },
                            width: 100,
                            dataIndex: 'nomer',
                            menuDisabled: true,
                            text: 'Номер'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 85,
                            dataIndex: 'sdate',
                            menuDisabled: true,
                            text: 'дата пост',
                            format: 'd-m-Y'
                        },
                        {
                            xtype: 'datecolumn',
                            width: 85,
                            dataIndex: 'pdate',
                            menuDisabled: true,
                            text: 'Поверка',
                            format: 'd-m-Y'
                        },
                        {
                            xtype: 'gridcolumn',
                            width: 65,
                            dataIndex: 'edizm',
                            menuDisabled: true,
                            text: 'Ед.изм'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 80,
                            dataIndex: 'koef',
                            menuDisabled: true,
                            text: 'коеф'
                        },
                        {
                            xtype: 'numbercolumn',
                            width: 77,
                            dataIndex: 'area',
                            menuDisabled: true,
                            text: 'S (м&sup2;)'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 300,
                    margin: '5 0 5 0',
                    style: 'background-color: #C2D9C9;',
                    width: 777,
                    layout: 'absolute',
                    title: '',
                    items: [
                        {
                            xtype: 'gridpanel',
                            x: 5,
                            y: 5,
                            id: 'grAllPokAppTeplomera',
                            itemId: 'grAllPokAppTeplomera',
                            width: 400,
                            title: 'История показаний тепломера',
                            store: 'StAllPokTeplomera',
                            columns: [
                                {
                                    xtype: 'datecolumn',
                                    width: 80,
                                    dataIndex: 'data',
                                    menuDisabled: true,
                                    text: 'дата',
                                    format: 'd-m-Y'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 81,
                                    dataIndex: 'pred',
                                    menuDisabled: true,
                                    text: 'пред',
                                    format: '0.000'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 73,
                                    dataIndex: 'tek',
                                    menuDisabled: true,
                                    text: 'тек',
                                    format: '0.000'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 73,
                                    dataIndex: 'qty',
                                    menuDisabled: true,
                                    text: 'кол-во',
                                    format: '0.000'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 90,
                                    dataIndex: 'gkal',
                                    menuDisabled: true,
                                    text: 'Гкалл',
                                    format: '0.000000'
                                }
                            ]
                        },
                        {
                            xtype: 'fieldcontainer',
                            x: 410,
                            y: 5,
                            height: 260,
                            style: 'background-color: #DCDCDC;',
                            width: 165,
                            layout: 'anchor',
                            fieldLabel: 'показание',
                            labelAlign: 'top',
                            items: [
                                {
                                    xtype: 'datefield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    fieldLabel: 'Дата',
                                    labelWidth: 50,
                                    name: 'data',
                                    readOnly: true,
                                    altFormats: 'd-m-Y|m/d/Y|n/j/Y|n/j/y|m/j/y|n/d/y|m/j/Y|n/d/Y|m-d-y|m-d-Y|m/d|m-d|md|mdy|mdY|d|Y-m-d|n-j|n/j',
                                    format: 'd-m-Y'
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    fieldLabel: 'пред',
                                    labelWidth: 50,
                                    name: 'pred',
                                    readOnly: true,
                                    decimalPrecision: 6
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    fieldLabel: 'текущ',
                                    labelWidth: 50,
                                    name: 'tek',
                                    hideTrigger: true,
                                    decimalPrecision: 6
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    fieldLabel: 'К-во',
                                    labelWidth: 50,
                                    name: 'qty',
                                    readOnly: true,
                                    decimalPrecision: 6
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    fieldLabel: 'Гкал',
                                    labelWidth: 50,
                                    name: 'gkal',
                                    readOnly: true,
                                    decimalPrecision: 6
                                }
                            ]
                        },
                        {
                            xtype: 'fieldcontainer',
                            x: 580,
                            y: 5,
                            height: 260,
                            style: 'background-color: #DCDCDC;',
                            width: 180,
                            layout: 'anchor',
                            fieldLabel: 'начислено',
                            labelAlign: 'top',
                            items: [
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    fieldLabel: 'Гкал/м&sup2;',
                                    labelWidth: 50,
                                    name: 'gkm2',
                                    readOnly: true,
                                    decimalPrecision: 6
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    fieldLabel: 'Тариф',
                                    labelWidth: 50,
                                    name: 'tarif',
                                    readOnly: true,
                                    decimalPrecision: 3
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    fieldLabel: 'S (м&sup2;)',
                                    labelWidth: 50,
                                    name: 'area',
                                    readOnly: true
                                },
                                {
                                    xtype: 'numberfield',
                                    anchor: '100%',
                                    padding: '0 5 0 5',
                                    fieldLabel: 'отопл',
                                    labelWidth: 50,
                                    name: 'otoplenie',
                                    readOnly: true
                                },
                                {
                                    xtype: 'fieldset',
                                    anchor: '100%',
                                    height: 90,
                                    padding: '0 5 0 5',
                                    style: 'background-color: #F1EEEE ;',
                                    width: 150,
                                    title: 'Бюджет',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            fieldLabel: 'S льг (м&sup2;)',
                                            labelWidth: 65,
                                            name: 'area_lg',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            fieldLabel: 'Бюджет',
                                            labelWidth: 50,
                                            name: 'budjet',
                                            readOnly: true
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});