/*
 * File: app/view/flat/TabAppVodomer.js
 * Date: Thu May 21 2020 17:42:54 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osmd.view.flat.TabAppVodomer', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.tabAppVodomer',

    requires: [
        'Osmd.view.flat.TabAppVodomerViewModel',
        'Ext.form.Panel',
        'Ext.grid.Panel',
        'Ext.view.Table',
        'Ext.grid.column.Number',
        'Ext.grid.column.Date',
        'Ext.panel.Tool',
        'Ext.form.FieldContainer',
        'Ext.form.field.Date',
        'Ext.form.field.Number',
        'Ext.form.FieldSet',
        'Ext.form.field.Hidden'
    ],

    viewModel: {
        type: 'tabAppVodomer'
    },
    hidden: true,
    id: 'tabAppVodomer',
    layout: 'fit',
    title: 'Водомеры',

    items: [
        {
            xtype: 'form',
            id: 'fmVodomer',
            scrollable: true,
            bodyPadding: 10,
            icon: '',
            title: '',
            items: [
                {
                    xtype: 'gridpanel',
                    id: 'grAppHVodomer',
                    itemId: 'grAppHVodomer',
                    margin: '5 0 15 0',
                    width: 720,
                    animCollapse: true,
                    collapsed: true,
                    collapsible: true,
                    title: 'счетчики воды снятые с учета',
                    emptyText: 'Приборов учета снятых с учета нет',
                    store: 'StHVodomer',
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'address_id',
                            text: 'Address_id'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'raion',
                            text: 'House_id'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'period',
                            text: 'Address'
                        },
                        {
                            xtype: 'gridcolumn',
                            text: 'Характеристика водомера',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        metaData.style = 'color:#D10000;font-weight:bold;';
                                        var retValue = '';
                                        switch (value) {
                                            case 'Хвода':
                                            retValue ='<span><img clas="icon" src="resources/css/images/ico/pipex.png"/></span>';
                                            break;
                                            case 'Гвода':
                                            retValue ='<span><img clas="icon" src="resources/css/images/ico/pipeg.png"/></span>';
                                        }
                                        return retValue;
                                    },
                                    width: 55,
                                    dataIndex: 'voda',
                                    menuDisabled: true,
                                    text: 'вода'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 80,
                                    dataIndex: 'place',
                                    menuDisabled: true,
                                    text: 'место'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 95,
                                    dataIndex: 'model',
                                    menuDisabled: true,
                                    text: 'модель',
                                    flex: 0
                                },
                                {
                                    xtype: 'numbercolumn',
                                    width: 102,
                                    dataIndex: 'nomer',
                                    menuDisabled: true,
                                    text: 'номер',
                                    format: '0'
                                }
                            ]
                        },
                        {
                            xtype: 'gridcolumn',
                            text: 'Установлен',
                            columns: [
                                {
                                    xtype: 'datecolumn',
                                    width: 75,
                                    dataIndex: 'sdate',
                                    text: 'дата ',
                                    format: 'd-m-Y'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 75,
                                    dataIndex: 'zplomba',
                                    menuDisabled: true,
                                    text: 'пломба'
                                }
                            ]
                        },
                        {
                            xtype: 'datecolumn',
                            menuDisabled: true,
                            text: 'Снятие с учета',
                            columns: [
                                {
                                    xtype: 'datecolumn',
                                    width: 75,
                                    dataIndex: 'data_spis',
                                    menuDisabled: true,
                                    text: 'дата',
                                    format: 'd-m-y'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 158,
                                    dataIndex: 'note',
                                    menuDisabled: true,
                                    text: 'инфо'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'gridpanel',
                    id: 'grAppVodomer',
                    itemId: 'grAppVodomer',
                    width: 721,
                    title: 'Счетчики воды ',
                    emptyText: 'Водомеров нет',
                    store: 'StVodomer',
                    columns: [
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            width: 61,
                            dataIndex: 'vodomer_id',
                            text: 'ид',
                            format: '0'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'address_id',
                            text: 'Address_id',
                            format: '0'
                        },
                        {
                            xtype: 'numbercolumn',
                            hidden: true,
                            dataIndex: 'raion',
                            text: 'House_id'
                        },
                        {
                            xtype: 'gridcolumn',
                            hidden: true,
                            dataIndex: 'period',
                            text: 'Address'
                        },
                        {
                            xtype: 'gridcolumn',
                            menuDisabled: true,
                            text: 'Характеристика водомера',
                            columns: [
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        metaData.style = 'color:#D10000;font-weight:bold;';
                                        var retValue = '';
                                        switch (value) {
                                            case 'Хвода':
                                            retValue ='<span><img clas="icon" src="resources/css/images/ico/pipex.png"/></span>';
                                            break;
                                            case 'Гвода':
                                            retValue ='<span><img clas="icon" src="resources/css/images/ico/pipeg.png"/></span>';
                                        }
                                        return retValue;
                                    },
                                    width: 55,
                                    dataIndex: 'voda',
                                    menuDisabled: true,
                                    text: 'вода'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        if (record.get('out')===1){
                                            metaData.tdCls = 'line-through';
                                        }
                                        return value;
                                    },
                                    width: 80,
                                    dataIndex: 'place',
                                    menuDisabled: true,
                                    text: 'место'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 95,
                                    dataIndex: 'model',
                                    menuDisabled: true,
                                    text: 'модель'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    renderer: function(value, metaData, record, rowIndex, colIndex, store, view) {
                                        if (record.get('out')===1){
                                            metaData.tdCls = 'line-through';
                                        }
                                        return value;
                                    },
                                    width: 102,
                                    dataIndex: 'nomer',
                                    menuDisabled: true,
                                    text: 'номер'
                                }
                            ]
                        },
                        {
                            xtype: 'gridcolumn',
                            menuDisabled: true,
                            text: 'Установлен',
                            columns: [
                                {
                                    xtype: 'datecolumn',
                                    width: 75,
                                    dataIndex: 'sdate',
                                    menuDisabled: true,
                                    text: 'дата',
                                    format: 'd-m-y'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 75,
                                    dataIndex: 'zplomba',
                                    menuDisabled: true,
                                    text: 'пломба'
                                }
                            ]
                        },
                        {
                            xtype: 'gridcolumn',
                            menuDisabled: true,
                            text: 'Поверка',
                            columns: [
                                {
                                    xtype: 'datecolumn',
                                    width: 75,
                                    dataIndex: 'sdate',
                                    menuDisabled: true,
                                    text: 'дата',
                                    format: 'd-m-y'
                                },
                                {
                                    xtype: 'datecolumn',
                                    width: 75,
                                    dataIndex: 'fpdate',
                                    menuDisabled: true,
                                    text: 'след',
                                    format: 'd-m-y'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    width: 80,
                                    dataIndex: 'plomba',
                                    menuDisabled: true,
                                    text: 'Пломба'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    height: 375,
                    width: 726,
                    title: '',
                    layout: {
                        type: 'hbox',
                        align: 'stretch'
                    },
                    items: [
                        {
                            xtype: 'gridpanel',
                            flex: 1,
                            height: 395,
                            id: 'grAllPokVodomera',
                            margin: '10 0 0 0',
                            width: 363,
                            title: 'История показаний прибора учета',
                            emptyText: 'Нет показаний по прибору учета',
                            store: 'StWater',
                            columns: [
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'address_id',
                                    text: 'Address_id'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    hidden: true,
                                    dataIndex: 'period',
                                    text: 'Address'
                                },
                                {
                                    xtype: 'numbercolumn',
                                    hidden: true,
                                    dataIndex: 'nomer',
                                    text: 'Nomer'
                                },
                                {
                                    xtype: 'datecolumn',
                                    hidden: true,
                                    dataIndex: 'data',
                                    text: 'Data'
                                },
                                {
                                    xtype: 'gridcolumn',
                                    menuDisabled: true,
                                    text: 'показания',
                                    columns: [
                                        {
                                            xtype: 'datecolumn',
                                            width: 75,
                                            dataIndex: 'fdate',
                                            menuDisabled: true,
                                            text: 'дата',
                                            format: 'd-m-y'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            width: 67,
                                            dataIndex: 'pred',
                                            menuDisabled: true,
                                            text: 'пред',
                                            format: '0'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            width: 67,
                                            dataIndex: 'tek',
                                            menuDisabled: true,
                                            text: 'тек',
                                            format: '0'
                                        },
                                        {
                                            xtype: 'numbercolumn',
                                            width: 65,
                                            dataIndex: 'kub',
                                            menuDisabled: true,
                                            text: 'кубы',
                                            format: '0'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridcolumn',
                                    dataIndex: 'operator',
                                    menuDisabled: true,
                                    text: 'оператор',
                                    flex: 1
                                }
                            ],
                            tools: [
                                {
                                    xtype: 'tool',
                                    callback: function(owner, tool, event) {
                                        //in use
                                        var grid = tool.findParentByType('grid');
                                        var fmVodomer = Ext.getCmp('fmVodomer');
                                        var vodomer_id = fmVodomer.getForm().findField('vodomer_id').getValue();
                                        //STORE
                                        var stUser = Ext.data.StoreManager.get("StUser");
                                        var stWater = Ext.data.StoreManager.get("StWater");
                                        //LOGIN & PASSWORD
                                        var values =stUser.getAt(0);

                                        //LOGIKA
                                        if(!Ext.isEmpty(vodomer_id)){
                                            stWater.removeAll();
                                            stWater.load({
                                                params: {
                                                    login:values.get('login'),
                                                    password:values.get('password'),
                                                    address_id:values.get('address_id'),
                                                    what:'AllPokVodomeraAll',
                                                    what_id: values.get('address_id'),
                                                    vodomer_id: vodomer_id
                                                },
                                                callback: function(records,operation,success){
                                                    if(success){
                                                        //console.log(grid);
                                                        grid.getView().refresh();
                                                    }
                                                },
                                                scope:this
                                            });
                                        }else{
                                            Ext.MessageBox.show({
                                                title: 'Просмотр истории показаний cчетчика воды',
                                                msg: "Выберите счетчик воды",
                                                buttons: Ext.MessageBox.OK,
                                                icon: Ext.MessageBox.INFO
                                            });
                                        }
                                    },
                                    tooltip: 'Загрузить все показания счетчика',
                                    type: 'search'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            flex: 1,
                            width: 350,
                            layout: 'absolute',
                            title: '',
                            items: [
                                {
                                    xtype: 'fieldcontainer',
                                    x: 10,
                                    y: 10,
                                    height: 190,
                                    style: 'background-color: #DCDCDC;',
                                    width: 170,
                                    layout: 'anchor',
                                    fieldLabel: 'показания, кубы',
                                    labelAlign: 'top',
                                    items: [
                                        {
                                            xtype: 'datefield',
                                            anchor: '100%',
                                            padding: '0 5 0 5',
                                            fieldLabel: 'Дата',
                                            labelWidth: 55,
                                            name: 'fdate',
                                            readOnly: true,
                                            altFormats: 'd-m-Y|m/d/Y|n/j/Y|n/j/y|m/j/y|n/d/y|m/j/Y|n/d/Y|m-d-y|m-d-Y|m/d|m-d|md|mdy|mdY|d|Y-m-d|n-j|n/j',
                                            format: 'd-m-Y'
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            padding: '0 5 0 5',
                                            fieldLabel: 'показ',
                                            labelWidth: 55,
                                            name: 'pok_id',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            padding: '0 5 0 5',
                                            fieldLabel: 'пред',
                                            labelWidth: 55,
                                            name: 'pred',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            padding: '0 5 0 5',
                                            fieldLabel: 'тек',
                                            labelWidth: 55,
                                            name: 'tek',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'textfield',
                                            anchor: '100%',
                                            padding: '0 5 0 5',
                                            fieldLabel: 'кубов',
                                            labelWidth: 55,
                                            name: 'kub',
                                            readOnly: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    x: 10,
                                    y: 210,
                                    height: 150,
                                    style: 'background-color: #DCDCDC;',
                                    width: 170,
                                    layout: 'anchor',
                                    fieldLabel: 'тарифы',
                                    labelAlign: 'top',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            padding: '0 5 0 5',
                                            fieldLabel: 'вода',
                                            labelWidth: 50,
                                            name: 'tarif_xv',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            padding: '0 5 0 5',
                                            fieldLabel: 'стоки',
                                            labelWidth: 50,
                                            name: 'tarif_st',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            padding: '0 5 0 5',
                                            fieldLabel: 'подог',
                                            labelWidth: 50,
                                            name: 'tarif_gv',
                                            readOnly: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    x: 190,
                                    y: 135,
                                    height: 230,
                                    style: 'background-color: #DCDCDC;',
                                    width: 160,
                                    layout: 'anchor',
                                    fieldLabel: 'по льготе',
                                    labelAlign: 'top',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            padding: '0 5 0 5',
                                            fieldLabel: 'вода',
                                            labelWidth: 50,
                                            name: 'lgota_xv',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            padding: '0 5 0 5',
                                            fieldLabel: 'стоки',
                                            labelWidth: 50,
                                            name: 'lgota_st',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            padding: '0 5 0 5',
                                            fieldLabel: 'подог',
                                            labelWidth: 50,
                                            name: 'lgota_gv',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'fieldset',
                                            anchor: '100%',
                                            height: 82,
                                            padding: '0 5 0 5',
                                            style: 'background-color: #F1EEEE ;',
                                            title: 'кубов по льготе',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    anchor: '100%',
                                                    width: 110,
                                                    fieldLabel: 'хвода',
                                                    labelWidth: 50,
                                                    name: 'xkub_lg',
                                                    readOnly: true
                                                },
                                                {
                                                    xtype: 'numberfield',
                                                    anchor: '100%',
                                                    width: 110,
                                                    fieldLabel: 'подог',
                                                    labelWidth: 50,
                                                    name: 'gkub_lg',
                                                    readOnly: true
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            hidden: true,
                                            fieldLabel: 'Label',
                                            name: 'address_id'
                                        },
                                        {
                                            xtype: 'datefield',
                                            anchor: '100%',
                                            hidden: true,
                                            fieldLabel: 'Label',
                                            name: 'data',
                                            format: 'Y-m-d'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'fieldcontainer',
                                    x: 190,
                                    y: 10,
                                    height: 120,
                                    style: 'background-color: #DCDCDC;',
                                    width: 160,
                                    layout: 'anchor',
                                    fieldLabel: 'начислено',
                                    labelAlign: 'top',
                                    items: [
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            padding: '0 5 0 5',
                                            fieldLabel: 'вода',
                                            labelWidth: 50,
                                            name: 'xvoda',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            padding: '0 5 0 5',
                                            fieldLabel: 'стоки',
                                            labelWidth: 50,
                                            name: 'stoki',
                                            readOnly: true
                                        },
                                        {
                                            xtype: 'numberfield',
                                            anchor: '100%',
                                            padding: '0 5 0 5',
                                            fieldLabel: 'подог',
                                            labelWidth: 50,
                                            name: 'gvoda',
                                            readOnly: true
                                        }
                                    ]
                                },
                                {
                                    xtype: 'hiddenfield',
                                    width: 145,
                                    fieldLabel: 'показ',
                                    labelWidth: 55,
                                    name: 'vodomer_id'
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]

});