/*
 * File: app/view/sprav/TabDbfLgotaViewController.js
 * Date: Sun Dec 01 2019 00:42:08 GMT+0200 (EET)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osmd.view.sprav.TabDbfLgotaViewController', {
    extend: 'Ext.app.ViewController',
    alias: 'controller.tabdbflgota',

    onDataNachLgotaChange: function(field, newValue, oldValue, eOpts) {

        //STORE
        var stUser = Ext.data.StoreManager.get("StUser");
        var values =stUser.getAt(0);
        var login = values.get('login');
        var password = values.get('password');

        var stSubsidia = Ext.data.StoreManager.get("StDbfLgota");
        var osmd_id =  Ext.getCmp('viborOsmdLgota').getValue();

        var btnGetSubsidiaOshadBank =  Ext.getCmp('btnGetLgotaOshadBank');
        var btnPrintLgotaReestrToOshadBank =  Ext.getCmp('btnPrintLgotaReestrToOshadBank');
        var btnPrintLgotaReestrFromOshadBank =  Ext.getCmp('btnPrintLgotaReestrFromOshadBank');
        var btnImportOshadBank =  Ext.getCmp('btnImportOshadBankLgota');
        var btnExportOshadBank =  Ext.getCmp('btnExportOshadBankLgota');
        var btnImportOplataOshad =  Ext.getCmp('btnImportOplataOshadLgota');
        var btnImportOplataOsmd =  Ext.getCmp('btnImportOplataOsmdLgota');
        var btnSubsidiaOtkatOsmd =  Ext.getCmp('btnLgotaOtkatOsmd');

        if (osmd_id){
            btnGetSubsidiaOshadBank.setDisabled(false);
            btnPrintLgotaReestrToOshadBank.setDisabled(false);
            btnPrintLgotaReestrFromOshadBank.setDisabled(false);
            btnImportOshadBank.setDisabled(false);
            btnExportOshadBank.setDisabled(false);
            btnImportOplataOshad.setDisabled(false);
            btnImportOplataOsmd.setDisabled(false);
            btnSubsidiaOtkatOsmd.setDisabled(false);

            stSubsidia.load({
                params: {
                    what:'getDbfLgota',
                    login:login,
                    password:password,
                    data:newValue,
                    osmd_id: osmd_id
                },
                scope:this
            });
        } else {
            btnGetSubsidiaOshadBank.setDisabled(true);
            btnPrintLgotaReestrToOshadBank.setDisabled(true);
            btnPrintLgotaReestrFromOshadBank.setDisabled(true);
            btnImportOshadBank.setDisabled(true);
            btnExportOshadBank.setDisabled(true);
            btnImportOplataOshad.setDisabled(true);
            btnImportOplataOsmd.setDisabled(true);
            btnSubsidiaOtkatOsmd.setDisabled(true);

        }

    }

});
