/*
 * File: app/view/sprav/WinEditOPlataViewModel.js
 * Date: Sun May 24 2020 01:17:00 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osmd.view.sprav.WinEditOPlataViewModel', {
    extend: 'Ext.app.ViewModel',
    alias: 'viewmodel.wineditoplata'

});