/*
 * File: app/view/menu/TabPnLeft.js
 * Date: Mon May 18 2020 18:28:52 GMT+0300 (EEST)
 *
 * This file was generated by Sencha Architect version 3.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 5.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 5.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('Osmd.view.menu.TabPnLeft', {
    extend: 'Ext.tab.Panel',
    alias: 'widget.tabpnleft',

    requires: [
        'Osmd.view.menu.TabPnLeftViewModel',
        'Ext.tab.Tab',
        'Ext.form.FieldSet',
        'Ext.form.Label',
        'Ext.form.field.ComboBox',
        'Ext.XTemplate',
        'Ext.form.field.Number',
        'Ext.tree.Panel',
        'Ext.tree.View'
    ],

    viewModel: {
        type: 'tabpnleft'
    },
    border: false,
    height: 678,
    id: 'tabPnLeft',
    animCollapse: true,
    collapseDirection: 'left',
    headerPosition: 'bottom',
    activeTab: 0,
    removePanelHeader: false,

    items: [
        {
            xtype: 'panel',
            border: false,
            id: 'tabMenuLifeFond',
            scrollable: true,
            header: false,
            title: 'жилой фонд',
            layout: {
                type: 'vbox',
                align: 'stretch'
            },
            tabConfig: {
                xtype: 'tab',
                frame: false,
                iconCls: 'icon-home'
            },
            items: [
                {
                    xtype: 'fieldset',
                    height: 71,
                    padding: '10 10 0 10',
                    style: 'background-color: #DCDCDC;',
                    title: '',
                    items: [
                        {
                            xtype: 'label',
                            hidden: true,
                            id: 'showAddress',
                            padding: '10 0 10 0',
                            style: 'color: #D15706; text-shadow: -1px -1px white, 1px 1px #333;font-size:14pt;text-align:left;',
                            width: 62,
                            text: 'Адрес'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            id: 'cbHouse',
                            padding: '5 5 0 5',
                            fieldLabel: '',
                            emptyText: 'Выбрать дом',
                            displayField: 'house',
                            queryMode: 'local',
                            store: 'StHouses',
                            valueField: 'house_id'
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    flex: 1,
                    id: 'listHouses',
                    padding: '5 5 5 5',
                    layout: 'fit',
                    collapseFirst: false,
                    title: '',
                    items: [
                        {
                            xtype: 'dataview',
                            cls: 'feed-list',
                            id: 'listHousesView',
                            scrollable: true,
                            style: 'background-color: #DCDCDC;',
                            tpl: [
                                '<tpl for="."><div class="feed-list-item">{item}</div></tpl>'
                            ],
                            emptyText: '',
                            itemSelector: '.feed-list-item',
                            overItemCls: 'feed-list-item-hover',
                            store: 'StAddress'
                        }
                    ]
                },
                {
                    xtype: 'numberfield',
                    flex: 1,
                    hidden: true,
                    id: 'indexTabLifeFond',
                    fieldLabel: 'Label',
                    name: 'indexTabLifeFond',
                    value: 0,
                    decimalPrecision: 0
                },
                {
                    xtype: 'numberfield',
                    flex: 1,
                    hidden: true,
                    id: 'indexTabOrg',
                    fieldLabel: 'Label',
                    name: 'indexTabOrg',
                    value: 4,
                    decimalPrecision: 0
                }
            ]
        },
        {
            xtype: 'panel',
            id: 'tabMenuSprav',
            scrollable: true,
            layout: 'fit',
            header: false,
            title: 'Инфо',
            tabConfig: {
                xtype: 'tab',
                flex: 1,
                iconCls: 'icon-sprav'
            },
            items: [
                {
                    xtype: 'treepanel',
                    id: 'treeMenuSprav',
                    title: '',
                    forceFit: true,
                    store: 'StTreeSprav',
                    rootVisible: false,
                    viewConfig: {
                        id: 'treeMenuSpravView',
                        style: 'background-color: #DCDCDC;',
                        loadingText: 'Загрузка...'
                    }
                }
            ]
        }
    ]

});